//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotingApp.Models.DbContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CellPhoneVotingEntities : DbContext
    {
        public CellPhoneVotingEntities()
            : base("name=CellPhoneVotingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblLogin> tblLogins { get; set; }
        public virtual DbSet<tblMainMenu> tblMainMenus { get; set; }
        public virtual DbSet<tblPole> tblPoles { get; set; }
        public virtual DbSet<tblPolesDetail> tblPolesDetails { get; set; }
        public virtual DbSet<tblRole> tblRoles { get; set; }
        public virtual DbSet<tblSubMenu> tblSubMenus { get; set; }
        public virtual DbSet<tblVote> tblVotes { get; set; }
    }
}
